version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip3 install --target ./package -r requirements.txt
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd package
      - zip -r ../deployment_package.zip .
      - cd ..
      - zip -r deployment_package.zip lambda_function.py service-account.json use_cases repos conf
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name RetroPixelApi --zip-file fileb://deployment_package.zip
      - echo "DONE!!"