name: Build and Deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Set secrets
      run: |
        echo 'SECRET=${{ secrets.SECRET }}' >> app/.env
        echo 'PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}' >> app/.env
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest==7.1.2
    - name: Test with pytest
      run: pytest
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Generate .zip file
      run: |
        pip3 install --target ./app -r requirements.txt
        cd app
        zip -r ../deployment_package.zip .
    - name: Deploy .zip to lambda
      run: |
        aws lambda update-function-code --function-name RetroPixelApi --zip-file fileb://deployment_package.zip